<html>
  <head>
    <title>dcSlider</title>
    <?php echo dcPage::jsPageTabs($default_tab);?>
  </head>
  <body>
    <h2><?php echo html::escapeHTML($core->blog->name);?> &gt; dcSlider</h2>
    <?php if (!empty($message)):?>
    <p class="message"><?php echo $message;?></p>
    <?php endif;?>

    <form action="<?php echo $p_url;?>" method="post" enctype="multipart/form-data">
    <?php if ($dcslider_active || $is_super_admin):?>
    <div class="multi-part" id="settings" title="<?php echo __('Settings');?>">
      <h3 class="hidden-if-js"><?php echo __('Settings');?></h3>
      <?php if ($is_super_admin):?>
      <div class="fieldset">
	<h3><?php echo __('Plugin activation');?></h3>
	<p>
	  <label class="classic" for="dcslider_active">
	    <?php echo form::checkbox('dcslider_active', 1, $dcslider_active);?>
	    <?php echo __('Enable dcSlider plugin');?>
	  </label>
	</p>
      </div>
      <?php endif;?>

      <?php if ($dcslider_active):?>
      <div class="fieldset">
	<h3><?php echo __('Content generated by plugin');?></h3>
	<p><?php echo __('Content generated by the plugin can be added automatically at the top of the home page. Otherwise, click on "installation" tab (or help button) to see how to insert it on your blog.');?></p>
	<p>
	  <?php echo form::checkbox('dcslider_automatic_content', 1, $dcslider_automatic_content);?>
	  <label class="classic" for="dcslider_automatic_content">
	    <?php echo __('Put automatically at the top of the home page?');?>
	  </label>
	</p>
      </div>
      <?php endif;?>
      <p>
	<input type="submit" name="saveconfig" value="<?php echo __('Save configuration');?>" />
      </p>
    </div>

    <?php if ($dcslider_active):?>
    <div class="multi-part" id="images" title="<?php echo __('Images');?>">
      <h3 class="hidden-if-js"><?php echo __('Images');?></h3>
      <p class="area">
	<label class="classic">
	  <?php echo __('List of images');?>
	  <?php echo form::textArea('dcslider_images', 5, 10, $dcslider_images);?>
	</label>
      </p>
      <p class="note"><?php echo __('Paths to images. One per line');?></p>

      <p>
	<input type="submit" name="saveconfig" value="<?php echo __('Add');?>" />
      </p>
    </div>

    <div class="multi-part" id="installation" title="<?php echo __('Installation');?>">
      <h3 class="hidden-if-js"><?php echo __('Installation');?></h3>
    </div>
    <?php endif;?>

    <input type="hidden" name="p" value="dcSlider"/>
    <?php echo $core->formNonce();?>
    </form>
    <?php endif;?>
    <?php dcPage::helpBlock('dcSlider');?>
  </body>
</html>
